import type { Metadata } from "next";
import Header from "@/components/shared/header";
import Sidebar from "@/components/shared/sidebar";
import { Toaster } from "@/components/ui/sonner"

import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

export const metadata: Metadata = {
  title: "notion-clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body>
        <Header />
        <div className="flex min-h-screen">
        <Sidebar></Sidebar>    
        <div className="flex-1 p-4 bg-gray-100 overflow-y-auto scrollbar-hide">{children}</div>
        <Toaster position='top-center'/>

        </div>
      </body>
    </html>
    </ClerkProvider>
  );
}
